// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SarcramentPlannerRazor.Models;

namespace SarcramentPlannerRazor.Migrations
{
    [DbContext(typeof(SarcramentContext))]
    [Migration("20180719230338_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SarcramentPlannerRazor.Models.SacProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClosingHymn")
                        .IsRequired();

                    b.Property<string>("ClosingPrayer")
                        .IsRequired();

                    b.Property<string>("Conducting")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("IntermediateHymn");

                    b.Property<string>("OpeningHymn")
                        .IsRequired();

                    b.Property<string>("OpeningPrayer")
                        .IsRequired();

                    b.Property<string>("SacramentHymn")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SacProgram");
                });

            modelBuilder.Entity("SarcramentPlannerRazor.Models.Speaker", b =>
                {
                    b.Property<int>("SpeakerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SacProgramID");

                    b.Property<string>("SpeakerName");

                    b.Property<string>("SpeakerOrder");

                    b.Property<string>("Topic");

                    b.HasKey("SpeakerID");

                    b.HasIndex("SacProgramID");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("SarcramentPlannerRazor.Models.Speaker", b =>
                {
                    b.HasOne("SarcramentPlannerRazor.Models.SacProgram", "SacProgram")
                        .WithMany("Speakers")
                        .HasForeignKey("SacProgramID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
